### PR TITLE
Fix encoding to make things UTF-8

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by ralphbean** [comment]
Why not encode all the fields, instead of just the few that are done here?  That way they would all be the same type (either bytes or unicode).

**Comment by pypingou** [comment]
sure can do

**Comment by ralphbean** [comment]
:+1:

**Comment by ralphbean** [comment]
Oh, is there a chance that any of those fields will be ``None``?

**Comment by pypingou** [comment]
Yeah, description could be, let me adjust it

**Comment by ralphbean** [comment]
OK, :+1: here.  :)

**Comment by pypingou** [comment]
Thanks for all

**Pull request merged**
