### PR TITLE
Syntax

### PR DESCRIPTION
**Pull request by tyll**
Fix syntax error and warning

### CODE REVIEW

**Comment by tyll** [comment]
regarding the datetime change: datetime.datetime was introduced in other lines of the script recently:
https://github.com/fedora-infra/packagedb-cli/blob/master/pkgdb2client/utils.py#L280

**Comment by pypingou** [comment]
Seems the commits show up in multiple PRs.

**Comment by tyll** [comment]
The PR #67  includes the commits from #66 because without the changes in #66, pkgdb-admin does not work. I do not know to handle this better, since afaics there is no way to tell github that PR #67 depends on PR #66.

**Comment by pypingou** [comment]
Ok looks good to me, thanks!

**Pull request merged**
