### PR TITLE
Raise an exception when unable to decode JSON.

### PR DESCRIPTION
**Pull request by ralphbean**
This partly addresses #34.

### CODE REVIEW

**Comment by relrod** [comment]
+1

**Comment by pypingou** [comment]
I wonder if this doesn't block running command with all, (retire all packages on all branches)

**Comment by ralphbean** [comment]
@pypingou, why would it?  I took a quick scan through ``cli.py`` but I don't see how.

**Comment by pypingou** [comment]
Yeah ok this shouldn't break anything :+1:

**Pull request merged**
